### PR TITLE
Fixes #32 and cleans up code a bit

### LINKED ISSUE #32: Mooshroom pet gives wrong item
## Description (Required)

The mooshroom pet gives mushroom stems instead of mushroom stew.

## Steps to reproduce the Issue (Required)

Put pet in inventory.

## Expected behavior (Required)

Should be giving stew instead of stem.

## Server Log / Error Report

No found errors.

## Environment (Required)

 - Minecraft Version:
 - CS-CoreLib Version: n/a
 - Slimefun Version: dev 867
 - HotbarPets Version: dev 36

### PR DESCRIPTION
**Pull request by WalshyDev**
* Fixes #32 
* Cleans up code a tad
* Changes tabs to spaces
* Moves base64 to hashes
* Moves all hashes to its own class

Head textures all still work:
image

also confirmed pet gives stew:
image

### CODE REVIEW

File: src/main/java/io/github/thebusybiscuit/hotbarpets/HeadTextures.java [hunk 1]
```diff
@@ -0,0 +1,68 @@
+package io.github.thebusybiscuit.hotbarpets;
+
+/**
+ * This class holds the head hashes for all head textures.
+ *
+ * @author WalshyDev
+ */
+public enum HeadTextures {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/hotbarpets/HeadTextures.java:8]: Shouldn't enums be singular and not plural?
Also I think `PetTexture` may be a better name here since we already got HeadTexture in Slimefun.

```suggestion
public enum PetTexture {
```

File: src/main/java/io/github/thebusybiscuit/hotbarpets/HeadTextures.java [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+
+    private final String hash;
+
+    HeadTextures(String hash) {
+        this.hash = hash;
+    }
+
+    public String getHash() {
+        return hash;
+    }
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/hotbarpets/HeadTextures.java:62]: Nonnull? :eyes:

File: src/main/java/io/github/thebusybiscuit/hotbarpets/HeadTextures.java [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/hotbarpets/HeadTextures.java:63]: Could also have an ItemStack shortcut method in here

File: src/main/java/io/github/thebusybiscuit/hotbarpets/HotbarPetsRunnable.java [hunk 4]
```diff
@@ -29,25 +29,19 @@ public void run() {
...
+                if (isPet(item, chicken) && chicken.checkAndConsumeFood(p)) {
+                    p.getInventory().addItem(new ItemStack(Material.EGG));
+                    p.getWorld().playSound(p.getLocation(), Sound.ENTITY_CHICKEN_EGG, 1.0F, 2.0F);
+                } else if (isPet(item, mooshroom) && mooshroom.checkAndConsumeFood(p)) {
+                    p.getInventory().addItem(new ItemStack(Material.MUSHROOM_STEW));
+                    p.getWorld().playSound(p.getLocation(), Sound.ENTITY_COW_AMBIENT, 1.0F, 2.0F);
+                } else if (isPet(item, fish) && fish.checkAndConsumeFood(p)) {
+                    p.getInventory().addItem(new ItemStack(Material.COOKED_COD));
+                    p.getWorld().playSound(p.getLocation(), Sound.BLOCK_WATER_AMBIENT, 1.0F, 2.0F);
                 } else if (isPet(item, goldenCow) && goldenCow.checkAndConsumeFood(p)) {
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/hotbarpets/HotbarPetsRunnable.java:45]: This is a big downgrade performance-wise.

If the item **is** a Chicken Pet but we don't have any food, we don't need to check if it is a mooshroom or a fish since we already know it is a Chicken.

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]
One big performance error here

File: src/main/java/io/github/thebusybiscuit/hotbarpets/HeadTextures.java (hunk 3 above)
Comment (WalshyDev) [reply src/main/java/io/github/thebusybiscuit/hotbarpets/HeadTextures.java:63]: That would mean moving a lot of other crap here too though.

Most usages are like so:
`new SlimefunItemStack("HOTBAR_PET_WITHER", PetTexture.WITHER_PET.getHash(), "&8Wither Pet", getName(), "&7Favourite Food: Soul Sand", "", "&fImmune to Wither Effect")`

If we changed that a total PetTexture.WITHER_PET.getItem("HOTBAR_PET_WITHER", "&8Wither Pet", getName(), "&7Favourite Food: Soul Sand", "", "&fImmune to Wither Effect")

It would not really save much code + create inconsistency for when it's a normal head rather than a custom one

Comment (TheBusyBiscuit) [reply src/main/java/io/github/thebusybiscuit/hotbarpets/HeadTextures.java]: No no no no, I meant a shortcut for where you did this:

`SkullItem.fromHash(PetTexture.CATEGORY.getHash())`

So we could instead just do 
`PetTexture.CATEGORY.getAsItem()`

File: src/main/java/io/github/thebusybiscuit/hotbarpets/PetTexture.java [hunk 5]
```diff
@@ -69,4 +72,9 @@ public String getHash() {
     public String toString() {
         return this.hash;
     }
+
+    @Nonnull
+    public ItemStack getAsItem() {
+        return SkullItem.fromHash(PetTexture.CATEGORY.getHash());
```
Comment (TheBusyBiscuit) [inline src/main/java/io/github/thebusybiscuit/hotbarpets/PetTexture.java:78]: ehhhm...
```suggestion
        return SkullItem.fromHash(getHash());
```

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]

**Comment by WalshyDev** [comment]
Also note: We need to update SF workflows. [Compile](https://github.com/Slimefun/Slimefun4/blob/master/.github/workflows/maven-compiler.yml#L27) uses @master which now is v2 so it wont compile there anymore.
[Discord Webhook](https://github.com/Slimefun/Slimefun4/blob/master/.github/workflows/discord-webhook.yml#L21) is also missing distribution so it'll fail

Keep in mind `distribution` is now required and 1.8 -> 8 - https://github.com/actions/setup-java#v2-vs-v1

Builds will have a dependabot PR soon if it doesn't already and it'll need the required changes or no builds will be pushed

**Review by TheBusyBiscuit — APPROVED** [review]
LGTM thanks ❤️
